export const menuConfig = [
    {
        key: "dashboard",
        link: "/dashboard",
        label: "Dashboard",
        icon: "DashboardOutlined",
        role: ["super-admin", "admin", "employee","manager"],
    },
    {
        key: "tasks",
        link: "/tasks",
        label: "Tasks",
        icon: "UnorderedListOutlined",
        role: ["super-admin", "admin", "employee","manager"],
    },
    {
        key: "users",
        link: "/users",
        label: "Users",
        icon: "UserOutlined",
        role: ["super-admin", "admin", "employee","manager"],
    },
    {
        key: "settings",
        link: "#",
        label: "Settings",
        icon: "SettingOutlined",
        role: ["super-admin", "admin"],
        children: [
            {
                key: "common",
                link: "/settings/common/",
                label: "Common",
                icon: "DashboardOutlined",
                role: ["super-admin", "admin"],
                children: [
                    {
                        key: "country",
                        link: "/settings/common/country",
                        label: "Country",
                        icon: "DashboardOutlined",
                        role: ["super-admin"],
                    },
                    {
                        key: "state",
                        link: "/settings/common/state",
                        label: "State",
                        icon: "DashboardOutlined",
                        role: ["super-admin"],
                    },
                    {
                        key: "cities",
                        link: "/settings/common/city",
                        label: "Cities",
                        icon: "DashboardOutlined",
                        role: ["super-admin"],
                    },
                    {
                        key: "region",
                        link: "/settings/common/region",
                        label: "Region",
                        icon: "DashboardOutlined",
                        role: ["super-admin"],
                    },
                    {
                        key: "sub-region",
                        link: "/settings/common/sub-region",
                        label: "Sub-Region",
                        icon: "DashboardOutlined",
                        role: ["super-admin"],
                    },
                ]
            },
            {
                key: "module",
                link: "/settings/module",
                label: "Module",
                icon: "DashboardOutlined",
                role: ["super-admin", "admin"],
            },
            {
                key: "resource-mapping",
                link: "/settings/resource-mapping",
                label: "Resource Mapping",
                icon: "DashboardOutlined",
                role: ["super-admin", "admin"],
            },
            {
                key: "acl",
                link: "/settings/acl",
                label: "Acl",
                icon: "DashboardOutlined",
                role: ["super-admin", "admin"],
            },
        ],
    },
];
